### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by muxmind** [pschichtel/VirtualECU#2]
Can you please provide a user document

**Comment by pschichtel** [comment]
@muxmind I've updated the readme a little. Can you be more specific about what you are struggling with?

**Comment by muxmind** [comment]
Once I download the zip file of your project. I don't find any .exe kind of file to run.

How to open VirtualECU, any GUI is there ?

Sorry may be I am asking very silly questions

**Comment by pschichtel** [comment]
it doesn't have a GUI and there is no exe. You can build the application using SBT and run it on the command like any java application. It's nto the most convenient of tools, but it get's the job done.

**Comment by muxmind** [comment]
Oh ! Thanks for the reply. I don't have any idea about SBT. Was asking in terms of end user and not as coder to develop it

**Comment by pschichtel** [comment]
yeah this is not really an end-user tool, it's meant more for someone that is building e.g. an OBD client application like a data logger.
